defaults:
  - _self_
  - task@_global_: quadruped_walk
  - override hydra/launcher: submitit_local

# task settings
frame_stack: 3
action_repeat: 1
discount: 0.99
# train settings
num_seed_frames: 4000
# eval
eval_every_frames: 10000
num_eval_episodes: 10
# snapshot
save_snapshot: true
# replay buffer
replay_buffer_size: 1000000
replay_buffer_num_workers: 4
nstep: 3
batch_size: 256
# misc
seed: 1
device: cuda
save_video: true
save_train_video: false
use_tb: false
# experiment
experiment: exp
# agent
lr: 1e-4
feature_dim: 256
use_wandb: false
wandb_group: None
name: drqv2_stn_aug
use_traj: false
lr_stn: 1e-4
img_size: 128
use_depth: true
hint: none

agent:
  _target_: algos.maniwhere.ManiAgent
  obs_shape: ??? # to be specified later
  action_shape: ??? # to be specified later
  device: ${device}
  lr: ${lr}
  lr_stn: ${lr_stn}
  critic_target_tau: 0.01
  update_every_steps: 2
  use_tb: ${use_tb}
  use_wandb: ${use_wandb}
  num_expl_steps: 2000
  hidden_dim: 1024
  feature_dim: ${feature_dim}
  stddev_schedule: ${stddev_schedule}
  stddev_clip: 0.3
  temp: 1
  aux_coef: 1
  aux_l2_coef: 1
  aux_tcc_coef: 1
  aux_latency: 150000
  

hydra:
  run:
    dir: ./exp_local/${now:%Y.%m.%d}/${name}/${now:%H%M%S}_${hydra.job.override_dirname}
  sweep:
    dir: ./exp/${now:%Y.%m.%d}/${name}/${now:%H%M}_${agent_cfg.experiment}
    subdir: ${hydra.job.num}
  launcher:
    timeout_min: 4300
    cpus_per_task: 10
    gpus_per_node: 1
    tasks_per_node: 1
    mem_gb: 160
    nodes: 1
    submitit_folder: ./exp/${now:%Y.%m.%d}/${name}/${now:%H%M%S}_${agent_cfg.experiment}/.slurm
